### ISSUE TITLE
The color of selected answer hurts my eyes.

### ISSUE THREAD

**Issue by fsailly** [djakpat/PlatiniumQuiz#7]
It's too flashy :(

**Comment by djakpat** [comment]
what color do you suggest?

**Comment by fsailly** [comment]
Can you provide me a panel in which i pick up an appropriate color ?

**Comment by djakpat** [comment]
https://material.io/guidelines/style/color.html#

**Comment by fsailly** [comment]
what is the current color code ? A200 ?

**Comment by djakpat** [comment]
yes

**Comment by GGI59** [comment]
It's ok now.
